update:
	rm -rf vendor/*
	# Vendor Management
	gvt fetch "github.com/Masterminds/glide"
	gvt fetch "github.com/FiloSottile/gvt"
	# go-vim tools
	gvt fetch "github.com/nsf/gocode"
	gvt fetch "github.com/alecthomas/gometalinter"
	gvt fetch "golang.org/x/tools/cmd/goimports"
	gvt fetch "golang.org/x/tools/cmd/guru"
	gvt fetch "golang.org/x/tools/cmd/gorename"
	gvt fetch "github.com/golang/lint/golint"
	gvt fetch "github.com/rogpeppe/godef"
	gvt fetch "github.com/kisielk/errcheck"
	gvt fetch "github.com/jstemmer/gotags"
	gvt fetch "github.com/klauspost/asmfmt/cmd/asmfmt"
	gvt fetch "github.com/fatih/motion"
	gvt fetch "github.com/zmb3/gogetdoc"
	gvt fetch "github.com/josharian/impl"
